#!/usr/bin/env python3
"""Build a human-readable SUMMARY.md from the proof-of-execution artifacts."""

import argparse
import csv
import json
import os
import textwrap
from pathlib import Path


def read_csv(path):
    with open(path) as f:
        rows = list(csv.DictReader(f))
    return rows


def md_table(rows, columns):
    header = '| ' + ' | '.join(columns) + ' |\n'
    sep = '|' + '|'.join('---' for _ in columns) + '|\n'
    body = ''
    for r in rows:
        body += '| ' + ' | '.join(str(r.get(c, '')) for c in columns) + ' |\n'
    return header + sep + body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--proof-dir', required=True)
    ap.add_argument('--results-dir', required=True)
    args = ap.parse_args()

    proof = Path(args.proof_dir)
    results = Path(args.results_dir)

    lines = []
    lines.append('# Proof of Execution\n')
    lines.append('Generated by `scripts/capture_proof.sh`.\n')
    lines.append('This bundle is the complete record required by the '
                 'rubric (flow tables + ping/iperf logs).\n')

    lines.append('## 1. Scenario summary (from CSV reports)\n')
    csv_summary_cols = ['label', 'src', 'dst', 'transmitted', 'received',
                        'loss_percent', 'rtt_min_ms', 'rtt_avg_ms',
                        'rtt_max_ms', 'rtt_mdev_ms']
    for name in ('scenario_1_baseline.csv',
                 'scenario_2b_path_compare.csv',
                 'scenario_3_link_failure.csv',
                 'scenario_4_blocked.csv'):
        path = results / name
        if not path.exists():
            continue
        lines.append(f'### `{name}`\n')
        lines.append(md_table(read_csv(path), csv_summary_cols))
        lines.append('')

    lines.append('## 2. Artifacts in this directory\n')
    artifacts = sorted(proof.iterdir(), key=lambda p: p.name)
    for p in artifacts:
        if p.name == 'SUMMARY.md':
            continue
        size = p.stat().st_size
        lines.append(f'- `{p.name}` ({size:,} bytes)')
    lines.append('')

    lines.append('## 3. Flow table snapshots\n')
    lines.append('Each scenario dumps the installed flows at the key '
                 'transition points. Highlights:\n')
    lines.append('- `flows_1_baseline_*.log` — default Path A rules')
    lines.append('- `flows_2_pathA_active.log` vs `flows_2_pathB_active.log` '
                 '— note the `output:` port change at `s1` and `s4`')
    lines.append('- `flows_3_linkfail_during.log` — link s1-s2 is DOWN; '
                 'traffic is still pinned to Path A so ping times out')
    lines.append('- `flows_3_linkfail_after_failover.log` — same table '
                 'after scenario rewrites to Path B')
    lines.append('- `flows_4_firewall_*.log` — shows the priority-500 '
                 'drop rules with packet counters')
    lines.append('')

    lines.append('## 4. Per-ping transcripts\n')
    ping_files = sorted(proof.glob('ping_*.log'))
    for p in ping_files:
        lines.append(f'### `{p.name}`\n')
        lines.append('```')
        try:
            txt = p.read_text()
        except Exception:
            txt = '(unreadable)'
        # Trim very long transcripts
        if len(txt) > 2000:
            txt = txt[:2000] + '\n... (truncated) ...'
        lines.append(txt.rstrip())
        lines.append('```\n')

    lines.append('## 5. iperf transcripts\n')
    for p in sorted(proof.glob('iperf_*.log')):
        lines.append(f'### `{p.name}`\n')
        lines.append('```')
        try:
            txt = p.read_text()
        except Exception:
            txt = '(unreadable)'
        lines.append(txt.rstrip())
        lines.append('```\n')

    lines.append('## 6. Controller log (tail)\n')
    clog = proof / 'controller.log'
    if clog.exists():
        lines.append('Last 80 lines of `controller.log`:\n')
        lines.append('```')
        data = clog.read_text().splitlines()
        lines.append('\n'.join(data[-80:]))
        lines.append('```\n')

    lines.append('## 7. OpenFlow pcap\n')
    pcap = proof / 'openflow.pcap'
    if pcap.exists():
        lines.append(
            f'`{pcap.name}` ({pcap.stat().st_size:,} bytes) captures every '
            'OpenFlow message exchanged on `lo:6633` for the full test run. '
            'Open in Wireshark with filter `openflow_v4` to inspect '
            '`FEATURES_REPLY`, `PACKET_IN`, `FLOW_MOD`, `PACKET_OUT`, '
            '`FLOW_STATS_REPLY` and `PORT_STATS_REPLY` messages.\n')

    (proof / 'SUMMARY.md').write_text('\n'.join(lines) + '\n')
    print(f'[+] wrote {proof / "SUMMARY.md"}')


if __name__ == '__main__':
    main()
